name: flutter_aws_s3_client
description: A simple, unofficial AWS S3 client in dart. Supports downloading objects and listing objects in a bucket.
version: 0.6.0
homepage: https://github.com/diagnosia/flutter_aws_s3_client
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.10.5'

dependencies:
  amazon_cognito_identity_dart_2: ^3.5.0
  built_value: ^8.6.1
  built_collection: ^5.1.1
  xml2json: ^6.1.0
  http: ^1.1.0
dev_dependencies:
  built_value_generator: ^8.6.1
  build_runner: ^2.4.6
